serviceMonitor:
  enabled: true
  additionalLabels:
    application.giantswarm.io/team: presales-demo
faults:
  error: false
  delay: false
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
    add:
      - NET_BIND_SERVICE