creation_rules:
- encrypted_regex: ^(data|stringData)$
  path_regex: management-clusters/golem/secrets/.*\.enc\.yaml
  pgp: 324cfb7564961ddef9dc9e9ed10982961bfeed2d
- encrypted_regex: ^(data|stringData)$
  path_regex: management-clusters/golem/organizations/presales-demo/workload-clusters/presales-demo-gitops/secrets/.*\.enc\.yaml
  pgp: 2814a24a77d4674278f037c11d6c535b10a9828a
