apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: presales-demo-gitops-podinfo
spec:
  catalog: podinfo
  name: podinfo
  namespace: default
  version: 6.7.0
  userConfig:
    configMap:
      name: presales-demo-gitops-podinfo-user-values
      namespace: org-presales-demo
