apiVersion: v1
data:
  values: |
    serviceMonitor:
      enabled: true
      additionalLabels:
        application.giantswarm.io/team: presales-demo
    faults:
      error: false
      delay: false
    resources:
      requests:
        cpu: 0.2
        memory: 200M
      limits:
        cpu: 0.4
        memory: 400M
kind: ConfigMap
metadata:
  name: presales-demo-gitops-podinfo-user-values
  namespace: org-presales-demo
