apiVersion: v1
data:
  values: |
    serviceMonitor:
      enabled: true
      additionalLabels:
        application.giantswarm.io/team: presales-demo
    faults:
      error: true
      delay: true
kind: ConfigMap
metadata:
  name: presales-demo-gitops-podinfo-user-values
  namespace: org-presales-demo
