apiVersion: v1
data:
  values: |
    podinfo:
      serviceMonitor:
        enabled: true
        labels:
          application.giantswarm.io/team: presales-demo
kind: ConfigMap
metadata:
  name: presales-demo-gitops-podinfo-user-values
  namespace: org-presales-demo
