apiVersion: v1
data:
    golem.abf9f28c551b78b8a0abde1c9159f2cfc49a3bed.asc: ENC[AES256_GCM,data:jnTQLSU/6315GpQXlomDZF0+TtWNf01ARkj7Z8Dxyq5pCyNFzisjJvFaRwjCsMH4ZRH2t2cxZ+dksWC48aFnz939JFU/bo0TXr9T6Lzmuju5TuKnk7pcqMVwSEYsXR3yRfGUJ8lR3hduplFVf1MwtFd5+xcKBKiW9tHPeZ7F6qz2ygi/COyWU8H484JdcJO93nqStpxSzYyY0OHdtLm6R+ltYDxrDidY88hYVDtFYeIreZrz6n43Dh2XR+NDKS4U+PaAcwIE1tJnmBxrxUUdM/zYeyNNM0WMyZGcdobEqndQfUrSkwFqJAqimHK/P9IopRpSxSGSu5SzXZY7G6WLk3fduslAmnVZMxMQfW8ShpQBNJZbd5lptSAYZO+afDZP7/DTHn2fLtzYAV4+mBDzQUGr3kg1YPiG2pAO+Cs2R9lNU7O9cdjIL3IYX6w3frXkjOc8DKH/IWMdgdchN3EQZuLV4Y+BOSMv9fPWf514SKM42YgbTHo68QjKFbqEMlH5SbLnRYGqZUgKFbpxXBt2sr4IA5t/IABXI8GjRoRf+PT/PVlGddKJbMMhoQFnC2jOy64uD0Syney5+AajZDAqESm0UbpjLu28WDZvHrDTJOzbyTaEz3pi227f4MmihdTS8iH8EbzKqa5vz6/0i5iyhm0YZQa++qGg//bc4e+R9GNGpVCWKz55tCkStE/TNP6rlwIEkCfaHFc5QKdqu3rx9umg1mjypAjpiQWDL+Df0qiH/M9I1P/widgHyNtF8q5uPAqs70/n2GqNQKPbg9MgBJpYHYho5M6/r+ut2M/D1zZF9/CHx5E6uhHjVFMNb90nXxxEhZMMVPScBR+ywCsPirWx+iEDRmJJoallSmj8dgwB77YBG7DEgJ4ZGVjnVs0+Z1lK6fo20dj65smFgHTrMI8h3Y3qiMPFFaJUcYJbXPSnEtLk/IYUSl++Uqa8QxhDVCa4X3OCLZNomtVq107o4xINZnMGRXGGV01wytmBTjdjpB/edaqsiXhyG6MBj8iu2jywvwWfeajW2oQC0I7ivyK3bJwOGyYM3dF3MOBRkxUECURwUG7rJ0R+hb2qNvgb3KjIGbdh6DpOb3rM2cCP/opmBe6BwzoDOGi9dml5UzsbW50FjIknU3oCjfkTx8C/Tbzihwzaa2AGRHn3yyS6c7iHWUwLgjexBPx+4L/GhOdox3Qjx1QAUU4pAUgVPWl3/CYWR/diCaDcU0lluKMs/id+kRy4A+lpuHPVFigW4+XOTcBrpPETDvYnWgXYAzGhpndTXo/XDJrvd68DmwaxiTJ0kKFKmR/2jMUtQev7UGVQG++RpHHU5c7YC09DCcfAnWLJAy4Pd355svefCgtGt8rXeaEemIm2,iv:q21iM0bt9UF1CGGjwJJ5uuye/A0XC0bnVWCLisqSIs0=,tag:7S0DX6/2ToII84pEPZ4+mA==,type:str]
kind: Secret
metadata:
    name: sops-gpg-master
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-15T11:36:22Z"
    mac: ENC[AES256_GCM,data:pd2hhlt3K/2OYUfcU3kZUpQ3xP4kBbRUCb9IyI8lH+3ArWg5HygeDht970NKsnMVpqhLXrZjezl39eM0eI5ek6kp6mY3vGinIUSk9+0t0GsJ1oY7io6h6IfjuPF419zpNksYGCtr7I/czDzNnXbolGtCEWVW0zB3DoSo29kWKcU=,iv:stj1RJILAtGKBkp2vOCEfNiIFOjzX1ZA5Px4JaTTr0M=,tag:Ml2f9TDZbyNpZ4YsqBEeog==,type:str]
    pgp:
        - created_at: "2024-07-15T11:36:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DNzH4EK+UgqESAQdABLFnSCq7MoCcSa2dtKLDvTXD2HJqlFe086MGVxENFggw
            twecZ/iFlMRpuT3VzgciVOukmm5Qgfdc88bIc/PuuoLlQjyuqz2ugNKz1OwLbjQQ
            0lEBees+SVrFEviMyOdIaJhmCUGR6YtGy8UxRl4BarLGHNjrbBRUoZ51OKdg13Cn
            RTTeu8wcsM+WM479pxoivOuOYEjgtTOhlJSfH8a588QyxGM=
            =M5uR
            -----END PGP MESSAGE-----
          fp: 720ad0385b7cc2f791fd69b44337287970388158
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
