apiVersion: v1
data:
    master.5e5352b5b01fcce86056189d81c46b55bf997c79.asc: ENC[AES256_GCM,data:CZzU0e8TcmCqs/+SWPmQb174Ueh/s93ENMuNN/3ngxCaGzAJ3BCERmbvm9h+7rfFqYnzVNR1raQanJfPhfWJ9eGVrjg/ZqbX9a2uvBTkdVbeArBaKTxVgBNEPChVyh7POvg5u7jD23HZ2GGsBkHAT7WFYY6FA69l0hoamm/iCgfqS6+O+czrIioBal6A359/R3BWOlKeRyTNhSKMxWNrhwj/UV9oBbOtiKYG+CsPXo6/SMePlJCLSBOrypBsIgd435WGgevbpMXvUc8eJRZHdsjMqOj6ZnPaqQ9K+cJQs5KuqnhOJW1+JEKbRl/JYSO4RjQhFCedJ1NIZWw2Rqjfte5hwAAevKIiZLdMtl9QaWaY4tkQrHlqGJvYBZjLqv2gjRMK3lU8lejKQEy04pQhDlF4g6/KGNJ5I1mSSlpD5+sZ+GnCxDsQsXX/i5HNeGcx1ov21GqaP1DF/EHuGeAxdbacKMBmG8qCYNDsTTTpVSC+2bg8suSu+UT4464XQ239D3QWQXGMJTixkJZ9xE5oHHNf4AQf2RXkLdVtsbZTkZ+8VQ1ktkpxhNryYMk9JF3iaplwyT4nT4h0BjFalJBB2uy2l09AjU2jyP1hyFwbI7eMyiw+er2rWVvLSQ0h0F916hO/wRdF/9L1n85uwhN+MKkxIC46a2lORdhZTSz417BnN/wzIU6OZh5a2t04YbS5tV2UPRHTAZm/WT5i+TExNeMSRvTEIEIIS8/+5FoCcsn1f8KWJXetwH8GB3yQwTSPe8xZzfVIVxt2AVetnE+KKTDynw/8SxsXpN2FCnjvo9AWPO+F5IrEdGtMyPJHgfi6wIIl3e+7arteHbMdpNnoSzKcP3w25+xwPpWoHC7AkhFiAD6L742f9yOxJb4YFRzQwFyhUpnFo3aNUNxY/ozUEl5DD0igqZyMYvqLMvaBzaIiENLdUhNXTM04uVuX01qwG3RYs3/Jb5sm6nS4FIcpfDjRiwmecC3sYkp60369XJf9uqkVCL/BtRj/tbmAHRspOgrQSmd9IX0Jg/2KLQFje5+AvfK/lwvlLys9XgoQA16yVisySK5Ta0PirBkliGRkCWF07Y+MMb/uysYCckDyRUPPL9T4uyUPxiljPoV7qNy06xGoY3naR02KQx9FMFCWee8jt99eSxG81Bck35nXDmmoIPivmawEPEs5dp6flctbNFBFnA+XT4iUUCt9Dp5c4LfynpNxqgYvNJBN5hnImN4vb4nx2Mk5+8s1/r0ur5OUHkuICr6SejEPHK2idGjSDWOuVboFkAs3byEyIQyg+vnhkgmmtMSOKbGuKx/PlD6dylFxRaMVgqUUJT38wdSKjm4fsXXUQC/40rgP2+wcH+LBw7bi0yO4,iv:XYNrbKT3pWPHInyc1sjT6l325wNI43q7SxWRuPnvi3M=,tag:mJe8edZhysKUG2JbmlDkRw==,type:str]
kind: Secret
metadata:
    name: presales-sops-gpg-master
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-15T12:00:34Z"
    mac: ENC[AES256_GCM,data:lGxQQjs9KemlGV0ZD7LVnyzEJ37vpDYewNzH5it6fIM3KlEcPH6hboVk01u006QCtBoOBUDiYfPhv41pd0Oz82y4/rt1Q3OYyWDA/DMrHu3Mqm5vlw8gNbPuAgYPNhEuRlKNfBFYOZlRbttwIxAYeNY5WuxXs+wfXxHwtclCsrs=,iv:OP1dhe7P2/bLS6lc0Ea5ZseGfz6YtwG4pYpPuBIKmaw=,tag:fnrYtUS8YYcg8WHRJVmCyg==,type:str]
    pgp:
        - created_at: "2024-07-15T12:00:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D8q/egEnJxgwSAQdA+XnJfhTOFNXQcM6wXqmGw2jF19RjEanbVTRPFL2xw1Ew
            8ocCvMU1tV/yCi+PpdlKQwb1jRFwBJOinyULwQXJY/uhfT/YHyIqm8/7epmQOh7o
            0lEBggXNi0hLFcnms4g0Xg2L0tSO2D1vAjitXuWQnOpzhCe7lJUBSxAtUqbZlFOj
            CeIGoxKVYK81HX0woJWew1vlNBhs9lUgYBkLysD6cFlAre0=
            =jLVC
            -----END PGP MESSAGE-----
          fp: 5e5352b5b01fcce86056189d81c46b55bf997c79
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
