apiVersion: v1
data:
    presales-demo-gitops.2814a24a77d4674278f037c11d6c535b10a9828a.asc: ENC[AES256_GCM,data:gUSNgEnTanqtmoyCjJl6LhxQoMCITWKDML9ea+brUF04YWSt22psZBda1XCTq+8H4R1RNFUnGbmbN7B2MtkvDYOB156OFp1svdQlVbBph6iF6ZQZ+U1JG27Lt4HvxkovQwv7IRQOGmaf2bSQ3xh3Vt8qJYKXvRdKwXQOxRk5wfSXlF4+7+sLq+BgmqDMOkJcm2dHSa1KtO98SU/wY71iBt/elOJyhVEDToFw+s0c/saW0lZijYNoKVnbVDrjQgbYLGjCK8uPaev5EFMp61baxwzYLSsxbG9hbJbOsrAHHKqm40TjHZR4v6uw3Sv991Xu1E3nsQUePjtF5Bt44vRfUm5svpaS27jCU3gyRQNKVZ8uRcp2/YO3V0GuXMUjgIvNsCkvxc0RmDygOEqhmzg/NxAzTHERl06OIlxhqSD3/vqaf27zOupo/aFTF9gb9aSKJ4Kcaq4ASWA3bKGcd4WLm5qJjGSRwufA0rxOffdpgmzIoH7gAB1KYQP/0/tulOeAmgUV21TSGUNEa7sCXDW0361AjDuwIdHJ9Q4Y3YOT4TtaLbCYHmI/OQZTTfDI6RO9x4Btt3mwHoHr7ezkYCZhebKx09X2mRCIHLVx81w0cBh8hk/kT+OEaBmukc9kQRz7ILi+sSRuhQOoSdM632VPDvxWIMsMSzSZ5fseuh1hEzLP4fRsuvihmg4RMQfPT6I0jWVqNWV9Bmb/YdaKzMPs+nWziQuLFM2P9BTALYijGLhlM9lJ16n0G1c4QAWAUb09Ugov9QmQ8h8k3wu90/Cvi9yjiSR60zM6jT1YGDhe3n8P+4DLxlB9ldDCLrjzItBMrLYohDPDdiGqogWU5v01UqZs75d2yVckm4EyUm3vuCSdjgtBez4H4ymMopIyDoXJODcJPoCW2OgI/bJttc+WCJAPixZw5YfP0hF9dakGbolSJbV8O/5r0WwEh+6g0FnrAfyzWodwTaWN50C1LlqM2R0QVEmKOP/d7ukmRG/8j4g8UilYTqkOaS0Wb8AP/AH5JNwE5IIgjK+yFlkFq4zyFCdvlMj1zVBygqOHix9ggXSjYXUFARa9IZrCX+ZMeNbSPuT45SKs/gNT2/fS347j2cJC5S1OTn2Mwr851by0XYcdITwViAx+LV3N+KFFEHjiz7pZdcsRU2OatWaH9XKKI7ly60SzLRs+KVd9HHS/ReEC2wzZg9gVO+hR/dFXfdLNndB+1xLKxY0TlLwKa/5kDIsLEhSW++xufp/py3rWaglu7l1alBC3UPGN0OJkvQw8Nel5WTFpi9+9PAqcqp3INRcnfKBtncMyHpm80r6HFj/xZEJ+INPbEGVaKPinygFujrHa0py17uGax2D9cm4An5KIpLr97yoj5gtx6/DaANSWkSJvxsqfK5ZBzVUQHwAHK4mNX6yoIyzlU/O/jIoa6S2GV866lkEjqPZv/67xuCcO7pmb,iv:72s3SBYs7GpMZk4zh3uy4uH8qdA9KjO5M9vH8STezqw=,tag:dHlknxTty1K+ymdAV4j5kA==,type:str]
kind: Secret
metadata:
    name: sops-gpg-presales-demo-gitops
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-25T08:52:37Z"
    mac: ENC[AES256_GCM,data:+DeN5iTgAl/Yf5o4gRjF35YMWWH0cSsXlUfwDwk0A5LSNFaX0eUE7LX8JOw7II4jX50WCGIpg8tSfO81bsBwjkBeFIueeXR+4sDnBavHBqNkIRmTGNvQtINcHFMLxFPHBWFwNWQd4Ubo/z2yvTmOxyREuvh+PaSfzZPiVraI2kM=,iv:1B06oIMlDLus6R6LA4+SJiQBNMurAw5ChRspNdXCVBs=,tag:W45NpT3vkDO1N50Ix0TTig==,type:str]
    pgp:
        - created_at: "2024-07-25T08:52:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DPdc/XYtWl6kSAQdAE4M2PqnYnPtlAqejns31GFdptOYdoAPh78tU6WLdznkw
            ZeaAO+qsvUw80t/oOxFIEpskNsMzYFDGK52EKx5TQgCNPFcJ+M+i0UFKhXkeIz0C
            0lEB2TrfPHJNfdLDPLORnNBNbHvrUxBfVdJ/8Tsr5w7yLoGrw35BSV2BA+AX0qwN
            hmViZ92ehdY8uOwdlsEbop3LKB++ynw4VXNExlIhPyEAXaM=
            =MDIw
            -----END PGP MESSAGE-----
          fp: 324cfb7564961ddef9dc9e9ed10982961bfeed2d
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
