apiVersion: v1
data:
    presales-demo-gitops.2814a24a77d4674278f037c11d6c535b10a9828a.asc: ENC[AES256_GCM,data:RV93j3UlsPMC+HgOeB3t0NDMYbTEcaZNThxTppsI50gWDdz5GOL3o1DFcrygjDMESJK8FYzIIO1mwNk29C173DvQfpp3cexQQWcGAYwdkdFr5QFLQ3sK64eBilReh7FLSQiyG1ue5sHkJ2lGaedpqL5VhDdIDx8YaT6aupcR7kSBmRHob3AE2/Ly7rTWgbj0GkFYw9+eDc3QpkHCgTOl9Re7BwJJJ+ho7HXkWmxze2K7mUJz8OWc8N+fhGr8W5aYUh4gPo5amZUPzLvEJnCco+gbGS0GQMHQ5S3kczcGz8a9X+JxKHcdv1hl2gMRqc7zVYpZjosorusJwgNzIbemMgL9VWRVQ9yI593fNJBwpKsplV2eTAOJCg8LHJ/clXWzqouqKkxXBg62PvZNAciwTS/KUUDMmpxBo6tEPWHMQP+eeON2Us4FJzbLf4EvVAsxSaXGKc23Bee5SYA1nYG0nMQpCcqEuSQGtObscjY+8/XGvkLGTxBpl72sZh4tjvdz9PofFMThbEiY+uV7JZw9Clgvt4dOHmvuVbw5QoRjMsi3el6omheo67oKJWLcF140j3MCIbwF51ZRlsUQCgb+cXSgajR6tty7/CZkCSgw854Xpl2Jg22kFoglOFd9vYrZ7FGibSXig0rSgVn24MqQ1eGlQtrC/ZuCWwxQUlfBYtq6C3Gqh7cFoHDk3U7RwKzr+COnz7vbm3D5SeoPwn6/Zig9XG93g3BrQKj3N2SLV++CaYsh41oEzRtBCLh3uMR54lT8nbxDY3c3lrp1QL7ueNMJik2jBBx3kJvPdx1c467mET67jzJopp7FxgYqlJt81QU4c5KBh05jpVWVBOKUvDfMu9juB0hSsp/SSBGC6XFGGYrQxkBSj4ZthXRn5fwybGwtsg1KaSKT86RiRRGczXZFXA0JpJ49eWFleCqy+8F+k/Owyb4O0cjH1O+9CcLD3eNTN7R+BObXuZvH96ST9IIz49uLDZdQUB+P8Uk4hT/72QR1Cpb3tekoJejcVhmbraudtzhQBFqwbwTgE/osyNdAW1Jit9A6jKfWIXVGNJ4yEKU+hWU8J3i26r2aFSbAl07LQ0tKtRZUNfONzz1jrDOlxzwsX5BNfTesv9qQb4cHYxyormZ4XgfAudrAWqObtlA/XF5ot/VYWsjjqfGQ59XW3dPi7OnaIoST/nRYrD4iJ/9vlx82qSlGtMNrOg0i6djJGHfpKvB+UpYPu9LJ15GpCRTeHsViueAM0bjEoUI2EoDmdlwCDUdJsF/E0y8dI98cwdMs/txyMi9FARq1Lbac1nlbhjz0NUr1Sfcf4q9ecB26hpipTGma7PrwvN2t/ULFZBEG8Y5A3zR+P9h7d3yFsHZaRw8x5pGuhdaR5Gw3EHXGwKUpbgFP48+7S+n8Ta1E4r4EArJLA2XtcetWVl/R6saufb0H952PndssKU3DlYZG,iv:QXHZoxpCqH1rTgT9wMgXB9s5VSI/7Kl41ZF5GH2Ma3U=,tag:SzphdV0PZCfe3uHInnforw==,type:str]
kind: Secret
metadata:
    name: sops-gpg-presales-demo-gitops
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-24T09:14:56Z"
    mac: ENC[AES256_GCM,data:ARafZAhXGxMbWvZDzje45/sT5/kLMeAKoHHoGXpscsv2rlBUSjM/cs2i52f389Ojag6kGorgvNraXk/Rta6lz4Po9i++IAm9TYTwipVEX5qYEp25rbETHv3tVd+Sz+iURVL3I6xATCSa+MHCKu1rLsIG/HnjafIYPFyiLj5wQ8I=,iv:iXoKgRJHuowWn4IescSanQTWFUYRLOhbLkLERERwWQo=,tag:fXBGauv4zAj18rQtZHGKQA==,type:str]
    pgp:
        - created_at: "2024-07-24T09:14:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DPdc/XYtWl6kSAQdAvLbh5nSV84rFLgF/P0kflaXgEPpXZ+Bmu8ATU6n2UmEw
            XSwaSqlP8Yhz9x9mmkSyDfYHWR+ijaRkdus/2cxO8lTc+EZnISpa8UjsdAVH+uBh
            0lEBwKNg5y44If2VTuRaKHRW1dPWR56phWeD63aL06O/oA5s1KJmFRP1VWCZaFCB
            01QdoE16wx0JiMbr2eSQiv2sxOjEbA0hbIrbrJfANSi084A=
            =nYgg
            -----END PGP MESSAGE-----
          fp: 324cfb7564961ddef9dc9e9ed10982961bfeed2d
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
