apiVersion: v1
kind: Secret
metadata:
    name: sops-gpg-presales-demo-gitops
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-24T09:14:56Z"
    mac: ENC[AES256_GCM,data:ARafZAhXGxMbWvZDzje45/sT5/kLMeAKoHHoGXpscsv2rlBUSjM/cs2i52f389Ojag6kGorgvNraXk/Rta6lz4Po9i++IAm9TYTwipVEX5qYEp25rbETHv3tVd+Sz+iURVL3I6xATCSa+MHCKu1rLsIG/HnjafIYPFyiLj5wQ8I=,iv:iXoKgRJHuowWn4IescSanQTWFUYRLOhbLkLERERwWQo=,tag:fXBGauv4zAj18rQtZHGKQA==,type:str]
    pgp:
        - created_at: "2024-07-24T09:14:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DPdc/XYtWl6kSAQdAvLbh5nSV84rFLgF/P0kflaXgEPpXZ+Bmu8ATU6n2UmEw
            XSwaSqlP8Yhz9x9mmkSyDfYHWR+ijaRkdus/2cxO8lTc+EZnISpa8UjsdAVH+uBh
            0lEBwKNg5y44If2VTuRaKHRW1dPWR56phWeD63aL06O/oA5s1KJmFRP1VWCZaFCB
            01QdoE16wx0JiMbr2eSQiv2sxOjEbA0hbIrbrJfANSi084A=
            =nYgg
            -----END PGP MESSAGE-----
          fp: 324cfb7564961ddef9dc9e9ed10982961bfeed2d
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
