apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: podinfo-policy-exception
  namespace: policy-exceptions
  labels:
    app: podinfo
  annotations:
    "giantswarm.io/exception-reason": "This is a demo on how to create a policyException to allow root user"
spec:
  exceptions:
    - policyName: disallow-capabilities-strict
      ruleNames:
        - autogen-require-drop-all
    - policyName: disallow-privilege-escalation
      ruleNames:
        - autogen-privilege-escalation
    - policyName: require-run-as-nonroot
      ruleNames:
        - autogen-run-as-non-root
        - run-as-non-root
    - policyName: restrict-seccomp-strict
      ruleNames:
        - autogen-check-seccomp-strict
        - check-seccomp-strict
  match:
    any:
      - resources:
          kinds:
            - Deployment
            - Pod
          names:
          - podinfo
          namespaces:
          - default
