apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/cluster: ${cluster_name}
    giantswarm.io/managed-by: cluster
  name: ${cluster_name}-default-apps
  namespace: org-${organization}
spec:
  catalog: cluster
  config:
    configMap:
      name: ${cluster_name}-cluster-values
      namespace: org-${organization}
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: default-apps-aws
  namespace: org-${organization}
  userConfig:
    configMap:
      name: ${cluster_name}-default-apps-config
      namespace: org-${organization}
  version: ${default_apps_release}
